#!/usr/bin/env bash

find . -name $1 | entr latexmk --quiet --pdf --synctex=1

#if [ $# -gt  0 ]; then
#    find . -name $1 | entr context --nonstopmode --synctex /_
#elif [ -r main.tex ]; then
#    find . -name main.tex | entr context --nonstopmode --synctex /_
#else
#    find . -path '*.tex' | sort -r | entr context --nonstopmode --synctex /_
#fi
