#!/usr/bin/env bash

# inspired by https://github.com/pixelastic/oroshi/blob/master/scripts/bin/npm-which

npm_bin="$(npm bin)"
bin_name=$1
local_path="${npm_bin}/${bin_name}"

if [ -f $local_path ];
then
    echo $local_path
else
    echo $(which $bin_name)
fi
