#!/usr/bin/env bash

if grep --quiet --regexp='\\bye' $1; then # it's plain TeX
    echo plain
elif grep --quiet --regexp='\\stoptext' $1; then # it's ConTeXt
    echo context
elif grep --quiet --regexp='fontspec' $1; then # it's probably XeLaTeX
    echo xelatext
elif grep --quiet --regexp='\\end{document}' $1; then # it's probably LaTeX
    echo latex
else # no idea what this is
    echo I'm not sure what the heck I'm looking at.
fi

#find . -name $1 | entr latexmk --quiet --pdf --synctex=1

#if [ $# -gt  0 ]; then
#    find . -name $1 | entr context --nonstopmode --synctex /_
#elif [ -r main.tex ]; then
#    find . -name main.tex | entr context --nonstopmode --synctex /_
#else
#    find . -path '*.tex' | sort -r | entr context --nonstopmode --synctex /_
#fi
